/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChangePassWdUser struct {
	// 新密码
	Password string `json:"password"`
	// 再次确认新密码
	Password1 string `json:"password1"`
	// user_id
	UserId int32 `json:"user_id"`
}
