/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListRegionTeamServices struct {
	Services []TeamServicesResp `json:"services"`
	Total int32 `json:"total"`
}
