/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EnterpriseSource struct {
	// 企业ID(联合云ID)
	EnterpriseId string `json:"enterprise_id"`
	// 使用的cpu
	UsedCpu float32 `json:"used_cpu"`
	// 使用的存储
	UsedDisk float32 `json:"used_disk"`
	// 使用的内存
	UsedMemory float32 `json:"used_memory"`
}
