/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateAdminUserReq struct {
	// 企业ID
	Eid string `json:"eid"`
	// 用户ID
	UserId string `json:"user_id"`
}
