/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TeamServicesResp struct {
	// 组件版本
	DeployVersion string `json:"deploy_version"`
	// 组id
	GroupId string `json:"group_id"`
	// 应用名称
	GroupName string `json:"group_name"`
	// 数据中心id
	RegionId string `json:"region_id"`
	// 组件昵称
	ServiceAlias string `json:"service_alias"`
	// 组件名称
	ServiceCname string `json:"service_cname"`
	// 组件id
	ServiceId string `json:"service_id"`
	// 组件类型
	ServiceType string `json:"service_type"`
	// 租户名称
	TenantName string `json:"tenant_name"`
	// 更新日期
	UpdateTime time.Time `json:"update_time"`
}
