/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type EnterpriseInfo struct {
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 企业别名
	EnterpriseAlias string `json:"enterprise_alias"`
	// 企业ID(联合云ID)
	EnterpriseId string `json:"enterprise_id"`
	// 企业名称
	EnterpriseName string `json:"enterprise_name"`
}
