/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AuthRequest struct {
	// 管理员密码
	Password string `json:"password"`
	// 管理员用户名
	Username string `json:"username"`
}
