/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Install struct {
	// 订单ID,通过订单ID去市场下载安装的应用元数据
	OrderId string `json:"order_id"`
}
